{
 "title": "PINPINPIN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "250ms",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "resolution",
    "query": "1s, 5s, 10s, 15s, 30s, 1m, 3m, 5m"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval]))",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Running Pods by Namespaces",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(namespace) ((kube_pod_container_status_running))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pod(FEP, Adaptor, DDS)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"default\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "DNP Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNP-Master CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"dnp-master\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "DNP-Master Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"dnp-master\"}) / sum(kube_pod_container_resource_limits{container=\"dnp-master\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "DNP Master Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"dnp-master.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"dnp-master.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "DNP-Slave CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"dnp-slave\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "DNP-Slave Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"dnp-slave\"}) / sum(kube_pod_container_resource_limits{container=\"dnp-slave\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "DNP Slave Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"dnp-slave.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"dnp-slave.*\", cluster=\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "IEC61850 Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "IEC61850 Server CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"iec-server\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "IEC61850 Server Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"iec-server\"}) / sum(kube_pod_container_resource_limits{container=\"iec-server\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "IEC61850 Server Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"iec-server.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"iec-server.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "IEC61850 Client CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"iec-client\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "IEC61850 Client Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"iec-client\"}) / sum(kube_pod_container_resource_limits{container=\"iec-client\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "IEC61850 Client Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"iec-client.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"iec-client.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "CIM Adaptor Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CIM Adaptor CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"cimadaptor\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "CIM Adaptor Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"cimadaptor\"}) / sum(kube_pod_container_resource_limits{container=\"cimadaptor\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "CIM Adaptor Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"cimadaptor.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"cimadaptor.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenDDS Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenDDS Pub CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"fep-pub-open\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "OpenDDS Pub Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"fep-pub-open\"}) / sum(kube_pod_container_resource_limits{container=\"fep-pub-open\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "OpenDDS Pub Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"fep-pub-open.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"fep-pub-open.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "OpenDDS Sub CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"fep-sub-open\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "OpenDDS Sub Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"fep-sub-open\"}) / sum(kube_pod_container_resource_limits{container=\"fep-sub-open\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "OpenDDS Sub Packet per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"fep-sub-open.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"fep-sub-open.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "RTI DDS Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "RTI DDS Pub CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"fep-pub-rti\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "RTI DDS Pub Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"fep-pub-rti\"}) / sum(kube_pod_container_resource_limits{container=\"fep-pub-rti\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "RTI DDS Pub Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"fep-pub-rti.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"fep-pub-rti.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "RTI DDS Sub CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100 * (rate(container_cpu_usage_seconds_total{container=\"fep-sub-rti\"}[1m])))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "RTI DDS Sub Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"fep-sub-rti\"}) / sum(kube_pod_container_resource_limits{container=\"fep-sub-rti\"}) * 100",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "RTI DDS Sub Packets per Second",
     "type": "timeseries",
     "description": "Average",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"default\", pod=~\"fep-sub-rti.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"default\", pod=~\"fep-sub-rti.*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  }
 ]
}