/* NetworkTopology_RecloserTopic */

module NWT{

	enum UnitSymbol {
		UnitSymbol_none,
		UnitSymbol_m
	};

	struct IdentifiedObject {
		string description;
		string mRID;
		string name;
		string aliasName;
	};

	struct Recloser {
		IdentifiedObject io;
		UnitSymbol us;
	};

	/* Topic */

	@topic
	struct RecloserTopic {
		Recloser r;
		@key
		long topicCount;
	};

};