apiVersion: v1
kind: Service
metadata:
  name: rti-service
spec:
  type: NodePort
  selector:
    app: rti
  ports:
    - name: pub-sub-port
      protocol: TCP
      port: 5432
      targetPort: 32
      nodePort: 30032