apiVersion: apps/v1
kind: Deployment
metadata:
    name: rti-deployment-sub
    #name: rti-deployment-pub
    #name: rti-deployment-db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rti
    template:
        metadata:
            labels:
                app: rti
        spec:
            containers:
            - name: sub-container
              image: sub-pod
              imagePullPolicy: Never
              securityContext:
                privileged: true
            #  command: ["java", "-cp", "../lib/*:.", "-Djava.library.path=../x64Linux4gcc7.3.0", "RecloserTopicSubscriber"]
              command: ["/bin/sh", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]
            #- name: pub-container
            #  image: pub-pod
            #  imagePullPolicy: Never
            #  securityContext:
            #    privileged: true
            #  command: ["/bin/sh", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]
            #- name: db-container
            #  image: postgres
            #  imagePullPolicy: Never
              #image: happykimyh/rti-db:v1
              #imagePullPolicy: Always
            #  command: ["/bin/sh", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]