apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: rti-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      nodeName: worker1
      containers:
      - name: pub
        image: happykimyh/rti_arm:v5.1
        imagePullPolicy: Always
        command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
        ports:
          - containerPort: 1213