apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: rti-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      nodeName: worker2
      containers:
      - name: sub
        image: happykimyh/rti_arm:v5.1
        imagePullPolicy: Always
        command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
        ports:
          - containerPort: 1223