/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module PIN {

// This must match the Messenger.idl in the DDS distribution,
// but the file is copied here to more accurately reflect a
// user's project setup.

  @topic
  struct PinJson {
    long count;
    @key long version;
    string body;
  };
};
