apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: opendds-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      nodeName: worker1
      containers:
      - name: pub
        image: happykimyh/opendds:v1.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
        ports:
          - containerPort: 1213

---

apiVersion: v1
kind: Service
metadata:
   name: pub-service
spec:
   selector:
     app: pub
   ports:
   - protocol: TCP
     port: 1213