# 23/10/15 Update
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: opendds-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      nodeName: worker2
      containers:
      - name: sub
        image: happykimyh/opendds:v1.4
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
        ports:
          - containerPort: 1223
---

apiVersion: v1
kind: Service
metadata:
   name: sub-service
spec:
   selector:
     app: sub
   ports:
    - protocol: TCP
      port: 1223

# rti
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: rti-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      nodeName: worker2
      containers:
      - name: sub
        image: happykimyh/rti_arm:v1
        imagePullPolicy: Always
        command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
        ports:
          - containerPort: 1223

---

apiVersion: v1
kind: Service
metadata:
   name: sub-service
spec:
   selector:
     app: sub
   ports:
   - protocol: TCP
     port: 1223